# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'detecta' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for detecta

  target 'detecta-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'detectaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'detecta-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for detecta-tvOS

  target 'detecta-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'OneSignal'
